### ISSUE TITLE
change challenge creation endpoints

### ISSUE THREAD

**Issue by cwdcwd** [cloudspokes/GLIB-mock#5]
- change /challenges to /github/challenge
- add /trello/webhook
- add /jira/challenge
- add /smartsheet/webhook
- add /gitlab/challenge

**Comment by gbockus** [comment]
For this dude we also want /gitlab/challenge

**Comment by cwdcwd** [comment]
correct

**Comment by cwdcwd** [comment]
changed this to `/challenge/:serviceType?`
In this fashion we can then field different service posting into GLIB
